/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

export enum GetAsyncAcceptEnum {
  applicationJson = "application/json",
  applicationXYaml = "application/x-yaml",
}

/**
 * Poll for the result of an asynchronous Code Sample preview generation.
 *
 * @remarks
 * Poll for the result of an asynchronous Code Sample preview generation.
 */
export async function codesamplesGetAsync(
  client: SDKCore,
  jobID: string,
  options?: RequestOptions & { acceptHeaderOverride?: GetAsyncAcceptEnum },
): Promise<
  Result<
    operations.GetCodeSamplePreviewAsyncResponse,
    | errors.ErrorT
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const input: operations.GetCodeSamplePreviewAsyncRequest = {
    jobID: jobID,
  };

  const parsed = safeParse(
    input,
    (value) =>
      operations.GetCodeSamplePreviewAsyncRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return parsed;
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    jobID: encodeSimple("jobID", payload.jobID, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/v1/code_sample/preview/async/{jobID}")(pathParams);

  const headers = new Headers({
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, application/x-yaml;q=0",
  });

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    operationID: "getCodeSamplePreviewAsync",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.GetCodeSamplePreviewAsyncResponse,
    | errors.ErrorT
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.stream(200, operations.GetCodeSamplePreviewAsyncResponse$inboundSchema, {
      ctype: "application/x-yaml",
    }),
    M.stream(200, operations.GetCodeSamplePreviewAsyncResponse$inboundSchema, {
      ctype: "application/json",
    }),
    M.json(202, operations.GetCodeSamplePreviewAsyncResponse$inboundSchema),
    M.jsonErr(["4XX", "5XX"], errors.ErrorT$inboundSchema),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return result;
  }

  return result;
}
